### ISSUE TITLE
Error on npm run development

### ISSUE THREAD

**Issue by saniko** [PatrickMennig/React-Boilerplate-Isomorhpic-App#1]
Even if I extract the mailConfig code into separated file,
App still runs with errors, none of the routes is working.

odule.js:442
    throw err;
    ^

Error: Cannot find module './mailConfig'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

FYI

**Comment by PatrickMennig** [comment]
I just checked it on my machine, there was a problem with a missing asset.
I've also added the default mailConfig.jsx for clarity.

Can you update the project and see if this has solved your problem?
If not, maybe you can tell me which version of node you are using.

Remember to run "development" twice or run "dev-client" and then run "development"... I'm still trying to figure out how to make isomorphic-tools wait for webpack to finish....

**Comment by PatrickMennig** [comment]
I'll close this issue as I'm unable to replicate it.
Please let me know if there are any further issues, then we can reopen it.
